language: go
sudo: false

matrix:
  include:
    - go: 1.2
    - go: 1.3
    - go: 1.4
    - go: 1.5
    - go: 1.5.1
    - go: 1.5.2
    - go: 1.5.3
    - go: 1.5.4
    - go: 1.6
    - go: 1.6.1
    - go: 1.6.2
    - go: tip

install:
  - # Skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -v -cover -race ./...
  - go test -bench=. ./...
